# kculture-db-secrets 라는 Kubernetes Secret에는 아래의 Key들이 반드시 들어가야 합니다.
# 이것은 샘플입니다.
apiVersion: v1
kind: Secret
metadata:
  name: kculture-db-secrets
type: Opaque
stringData:
  DB_HOST: "172.16.10.122"
  DB_USER: "admin"
  DB_PASSWORD: "DO_NOT_COMMIT_REAL_PASSWORD"
  DB_NAME: "kculture"
